package xxc42.data.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.EntityProperty;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;

import xxc42.data.PersonWithDbGeneratedUUID;

/**
 * Class _PersonWithDbGeneratedUUID was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _PersonWithDbGeneratedUUID extends BaseDataObject {

    private static final long serialVersionUID = 1L;

    public static final String ID_PK_COLUMN = "id";

    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);
    public static final ListProperty<PersonWithDbGeneratedUUID> CHILDREN = PropertyFactory.createList("children", PersonWithDbGeneratedUUID.class);
    public static final EntityProperty<PersonWithDbGeneratedUUID> LAST_ADDED_CHILD = PropertyFactory.createEntity("lastAddedChild", PersonWithDbGeneratedUUID.class);
    public static final EntityProperty<PersonWithDbGeneratedUUID> PARENT = PropertyFactory.createEntity("parent", PersonWithDbGeneratedUUID.class);

    protected String name;

    protected Object children;
    protected Object lastAddedChild;
    protected Object parent;

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void addToChildren(PersonWithDbGeneratedUUID obj) {
        addToManyTarget("children", obj, true);
    }

    public void removeFromChildren(PersonWithDbGeneratedUUID obj) {
        removeToManyTarget("children", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<PersonWithDbGeneratedUUID> getChildren() {
        return (List<PersonWithDbGeneratedUUID>)readProperty("children");
    }

    public void setLastAddedChild(PersonWithDbGeneratedUUID lastAddedChild) {
        setToOneTarget("lastAddedChild", lastAddedChild, true);
    }

    public PersonWithDbGeneratedUUID getLastAddedChild() {
        return (PersonWithDbGeneratedUUID)readProperty("lastAddedChild");
    }

    public void setParent(PersonWithDbGeneratedUUID parent) {
        setToOneTarget("parent", parent, true);
    }

    public PersonWithDbGeneratedUUID getParent() {
        return (PersonWithDbGeneratedUUID)readProperty("parent");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "name":
                return this.name;
            case "children":
                return this.children;
            case "lastAddedChild":
                return this.lastAddedChild;
            case "parent":
                return this.parent;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "name":
                this.name = (String)val;
                break;
            case "children":
                this.children = val;
                break;
            case "lastAddedChild":
                this.lastAddedChild = val;
                break;
            case "parent":
                this.parent = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.name);
        out.writeObject(this.children);
        out.writeObject(this.lastAddedChild);
        out.writeObject(this.parent);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.name = (String)in.readObject();
        this.children = in.readObject();
        this.lastAddedChild = in.readObject();
        this.parent = in.readObject();
    }

}
